### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by BackSeat** [natm/munin-plugins-aaisp#2]
There are some errors in the "Plugin config" section of the README.md/website:

1) The file path should be /etc/munin/plugin-conf.d/ (not pluginS-conf)
2) The environment variables that the script expects are 'aaispuser' and 'aaisppass', but the example config uses 'username' and 'password'.

**Comment by natm** [comment]
Thanks for pointing these out! corrected the README.md in this commit:

https://github.com/natm/munin-plugins-aaisp/commit/a80cd46f19a9e8575e42206dce0775dbf99252cc
